use Medicare;

CREATE TABLE [dbo].[jqGridSavedSearchHistories](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SearchType] [nvarchar](50) NULL,
	[ContactID] [int] NOT NULL,
	[Name] [nvarchar](255) NULL,
	[Search] [nvarchar](max) NULL,
	[Filter] [nvarchar](max) NULL,
	[CreationTime] [datetime] NULL,
 CONSTRAINT [PK_jqGridSavedSearchHistories] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [dbo].[jqGridSavedSearchHistories] ADD  CONSTRAINT [DF_jqGridSavedSearchHistories_CreationTime]  DEFAULT (getdate()) FOR [CreationTime]

CREATE TABLE [dbo].[MedicareProviders](
	[NPI] [int] NOT NULL,
	[Entity Type Code] [smallint] NULL,
	[Replacement NPI] [int] NULL,
	[Employer Identification Number (EIN)] [varchar](10) NULL,
	[Provider Organization Name (Legal Business Name)] [varchar](70) NULL,
	[Provider Last Name (Legal Name)] [varchar](35) NULL,
	[Provider First Name] [varchar](20) NULL,
	[Provider Middle Name] [varchar](20) NULL,
	[Provider Name Prefix Text] [varchar](5) NULL,
	[Provider Name Suffix Text] [varchar](5) NULL,
	[Provider Credential Text] [varchar](20) NULL,
	[Provider Other Organization Name] [varchar](70) NULL,
	[Provider Other Organization Name Type Code] [smallint] NULL,
	[Provider Other Last Name] [varchar](35) NULL,
	[Provider Other First Name] [varchar](20) NULL,
	[Provider Other Middle Name] [varchar](20) NULL,
	[Provider Other Name Prefix Text] [varchar](5) NULL,
	[Provider Other Name Suffix Text] [varchar](5) NULL,
	[Provider Other Credential Text] [varchar](20) NULL,
	[Provider Other Last Name Type Code] [smallint] NULL,
	[Provider First Line Business Mailing Address] [varchar](55) NULL,
	[Provider Second Line Business Mailing Address] [varchar](55) NULL,
	[Provider Business Mailing Address City Name] [varchar](40) NULL,
	[Provider Business Mailing Address State Name] [varchar](40) NULL,
	[Provider Business Mailing Address Postal Code] [varchar](20) NULL,
	[Provider Business Mailing Address Country Code (If outside US)] [varchar](2) NULL,
	[Provider Business Mailing Address Telephone Number] [varchar](20) NULL,
	[Provider Business Mailing Address Fax Number] [varchar](20) NULL,
	[Provider First Line Business Practice Location Address] [varchar](55) NULL,
	[Provider Second Line Business Practice Location Address] [varchar](55) NULL,
	[Provider Business Practice Location Address City Name] [varchar](40) NULL,
	[Provider Business Practice Location Address State Name] [varchar](40) NULL,
	[Provider Business Practice Location Address Postal Code] [varchar](20) NULL,
	[Provider Business Practice Location Address Country Code (If outside US)] [varchar](2) NULL,
	[Provider Business Practice Location Address Telephone Number] [varchar](20) NULL,
	[Provider Business Practice Location Address Fax Number] [varchar](20) NULL,
	[Provider Enumeration Date] [datetime] NULL,
	[Last Update Date] [datetime] NULL,
	[NPI Deactivation Reason Code] [varchar](2) NULL,
	[NPI Deactivation Date] [datetime] NULL,
	[NPI Reactivation Date] [datetime] NULL,
	[Provider Gender Code] [varchar](1) NULL,
	[Authorized Official Last Name] [varchar](35) NULL,
	[Authorized Official First Name] [varchar](20) NULL,
	[Authorized Official Middle Name] [varchar](20) NULL,
	[Authorized Official Title or Position] [varchar](35) NULL,
	[Authorized Official Telephone Number] [varchar](20) NULL,
	[Healthcare Provider Taxonomy Code_1] [varchar](10) NULL,
	[Provider License Number_1] [varchar](20) NULL,
	[Provider License Number State Code_1] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_1] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_2] [varchar](10) NULL,
	[Provider License Number_2] [varchar](20) NULL,
	[Provider License Number State Code_2] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_2] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_3] [varchar](10) NULL,
	[Provider License Number_3] [varchar](20) NULL,
	[Provider License Number State Code_3] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_3] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_4] [varchar](10) NULL,
	[Provider License Number_4] [varchar](20) NULL,
	[Provider License Number State Code_4] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_4] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_5] [varchar](10) NULL,
	[Provider License Number_5] [varchar](20) NULL,
	[Provider License Number State Code_5] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_5] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_6] [varchar](10) NULL,
	[Provider License Number_6] [varchar](20) NULL,
	[Provider License Number State Code_6] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_6] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_7] [varchar](10) NULL,
	[Provider License Number_7] [varchar](20) NULL,
	[Provider License Number State Code_7] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_7] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_8] [varchar](10) NULL,
	[Provider License Number_8] [varchar](20) NULL,
	[Provider License Number State Code_8] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_8] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_9] [varchar](10) NULL,
	[Provider License Number_9] [varchar](20) NULL,
	[Provider License Number State Code_9] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_9] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_10] [varchar](10) NULL,
	[Provider License Number_10] [varchar](20) NULL,
	[Provider License Number State Code_10] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_10] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_11] [varchar](10) NULL,
	[Provider License Number_11] [varchar](20) NULL,
	[Provider License Number State Code_11] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_11] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_12] [varchar](10) NULL,
	[Provider License Number_12] [varchar](20) NULL,
	[Provider License Number State Code_12] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_12] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_13] [varchar](10) NULL,
	[Provider License Number_13] [varchar](20) NULL,
	[Provider License Number State Code_13] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_13] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_14] [varchar](10) NULL,
	[Provider License Number_14] [varchar](20) NULL,
	[Provider License Number State Code_14] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_14] [varchar](1) NULL,
	[Healthcare Provider Taxonomy Code_15] [varchar](10) NULL,
	[Provider License Number_15] [varchar](20) NULL,
	[Provider License Number State Code_15] [varchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_15] [varchar](1) NULL,
	[Other Provider Identifier_1] [varchar](20) NULL,
	[Other Provider Identifier Type Code_1] [varchar](2) NULL,
	[Other Provider Identifier State_1] [varchar](2) NULL,
	[Other Provider Identifier Issuer_1] [varchar](80) NULL,
	[Other Provider Identifier_2] [varchar](20) NULL,
	[Other Provider Identifier Type Code_2] [varchar](2) NULL,
	[Other Provider Identifier State_2] [varchar](2) NULL,
	[Other Provider Identifier Issuer_2] [varchar](80) NULL,
	[Other Provider Identifier_3] [varchar](20) NULL,
	[Other Provider Identifier Type Code_3] [varchar](2) NULL,
	[Other Provider Identifier State_3] [varchar](2) NULL,
	[Other Provider Identifier Issuer_3] [varchar](80) NULL,
	[Other Provider Identifier_4] [varchar](20) NULL,
	[Other Provider Identifier Type Code_4] [varchar](2) NULL,
	[Other Provider Identifier State_4] [varchar](2) NULL,
	[Other Provider Identifier Issuer_4] [varchar](80) NULL,
	[Other Provider Identifier_5] [varchar](20) NULL,
	[Other Provider Identifier Type Code_5] [varchar](2) NULL,
	[Other Provider Identifier State_5] [varchar](2) NULL,
	[Other Provider Identifier Issuer_5] [varchar](80) NULL,
	[Other Provider Identifier_6] [varchar](20) NULL,
	[Other Provider Identifier Type Code_6] [varchar](2) NULL,
	[Other Provider Identifier State_6] [varchar](2) NULL,
	[Other Provider Identifier Issuer_6] [varchar](80) NULL,
	[Other Provider Identifier_7] [varchar](20) NULL,
	[Other Provider Identifier Type Code_7] [varchar](2) NULL,
	[Other Provider Identifier State_7] [varchar](2) NULL,
	[Other Provider Identifier Issuer_7] [varchar](80) NULL,
	[Other Provider Identifier_8] [varchar](20) NULL,
	[Other Provider Identifier Type Code_8] [varchar](2) NULL,
	[Other Provider Identifier State_8] [varchar](2) NULL,
	[Other Provider Identifier Issuer_8] [varchar](80) NULL,
	[Other Provider Identifier_9] [varchar](20) NULL,
	[Other Provider Identifier Type Code_9] [varchar](2) NULL,
	[Other Provider Identifier State_9] [varchar](2) NULL,
	[Other Provider Identifier Issuer_9] [varchar](80) NULL,
	[Other Provider Identifier_10] [varchar](20) NULL,
	[Other Provider Identifier Type Code_10] [varchar](2) NULL,
	[Other Provider Identifier State_10] [varchar](2) NULL,
	[Other Provider Identifier Issuer_10] [varchar](80) NULL,
	[Other Provider Identifier_11] [varchar](20) NULL,
	[Other Provider Identifier Type Code_11] [varchar](2) NULL,
	[Other Provider Identifier State_11] [varchar](2) NULL,
	[Other Provider Identifier Issuer_11] [varchar](80) NULL,
	[Other Provider Identifier_12] [varchar](20) NULL,
	[Other Provider Identifier Type Code_12] [varchar](2) NULL,
	[Other Provider Identifier State_12] [varchar](2) NULL,
	[Other Provider Identifier Issuer_12] [varchar](80) NULL,
	[Other Provider Identifier_13] [varchar](20) NULL,
	[Other Provider Identifier Type Code_13] [varchar](2) NULL,
	[Other Provider Identifier State_13] [varchar](2) NULL,
	[Other Provider Identifier Issuer_13] [varchar](80) NULL,
	[Other Provider Identifier_14] [varchar](20) NULL,
	[Other Provider Identifier Type Code_14] [varchar](2) NULL,
	[Other Provider Identifier State_14] [varchar](2) NULL,
	[Other Provider Identifier Issuer_14] [varchar](80) NULL,
	[Other Provider Identifier_15] [varchar](20) NULL,
	[Other Provider Identifier Type Code_15] [varchar](2) NULL,
	[Other Provider Identifier State_15] [varchar](2) NULL,
	[Other Provider Identifier Issuer_15] [varchar](80) NULL,
	[Other Provider Identifier_16] [varchar](20) NULL,
	[Other Provider Identifier Type Code_16] [varchar](2) NULL,
	[Other Provider Identifier State_16] [varchar](2) NULL,
	[Other Provider Identifier Issuer_16] [varchar](80) NULL,
	[Other Provider Identifier_17] [varchar](20) NULL,
	[Other Provider Identifier Type Code_17] [varchar](2) NULL,
	[Other Provider Identifier State_17] [varchar](2) NULL,
	[Other Provider Identifier Issuer_17] [varchar](80) NULL,
	[Other Provider Identifier_18] [varchar](20) NULL,
	[Other Provider Identifier Type Code_18] [varchar](2) NULL,
	[Other Provider Identifier State_18] [varchar](2) NULL,
	[Other Provider Identifier Issuer_18] [varchar](80) NULL,
	[Other Provider Identifier_19] [varchar](20) NULL,
	[Other Provider Identifier Type Code_19] [varchar](2) NULL,
	[Other Provider Identifier State_19] [varchar](2) NULL,
	[Other Provider Identifier Issuer_19] [varchar](80) NULL,
	[Other Provider Identifier_20] [varchar](20) NULL,
	[Other Provider Identifier Type Code_20] [varchar](2) NULL,
	[Other Provider Identifier State_20] [varchar](2) NULL,
	[Other Provider Identifier Issuer_20] [varchar](80) NULL,
	[Other Provider Identifier_21] [varchar](20) NULL,
	[Other Provider Identifier Type Code_21] [varchar](2) NULL,
	[Other Provider Identifier State_21] [varchar](2) NULL,
	[Other Provider Identifier Issuer_21] [varchar](80) NULL,
	[Other Provider Identifier_22] [varchar](20) NULL,
	[Other Provider Identifier Type Code_22] [varchar](2) NULL,
	[Other Provider Identifier State_22] [varchar](2) NULL,
	[Other Provider Identifier Issuer_22] [varchar](80) NULL,
	[Other Provider Identifier_23] [varchar](20) NULL,
	[Other Provider Identifier Type Code_23] [varchar](2) NULL,
	[Other Provider Identifier State_23] [varchar](2) NULL,
	[Other Provider Identifier Issuer_23] [varchar](80) NULL,
	[Other Provider Identifier_24] [varchar](20) NULL,
	[Other Provider Identifier Type Code_24] [varchar](2) NULL,
	[Other Provider Identifier State_24] [varchar](2) NULL,
	[Other Provider Identifier Issuer_24] [varchar](80) NULL,
	[Other Provider Identifier_25] [varchar](20) NULL,
	[Other Provider Identifier Type Code_25] [varchar](2) NULL,
	[Other Provider Identifier State_25] [varchar](2) NULL,
	[Other Provider Identifier Issuer_25] [varchar](80) NULL,
	[Other Provider Identifier_26] [varchar](20) NULL,
	[Other Provider Identifier Type Code_26] [varchar](2) NULL,
	[Other Provider Identifier State_26] [varchar](2) NULL,
	[Other Provider Identifier Issuer_26] [varchar](80) NULL,
	[Other Provider Identifier_27] [varchar](20) NULL,
	[Other Provider Identifier Type Code_27] [varchar](2) NULL,
	[Other Provider Identifier State_27] [varchar](2) NULL,
	[Other Provider Identifier Issuer_27] [varchar](80) NULL,
	[Other Provider Identifier_28] [varchar](20) NULL,
	[Other Provider Identifier Type Code_28] [varchar](2) NULL,
	[Other Provider Identifier State_28] [varchar](2) NULL,
	[Other Provider Identifier Issuer_28] [varchar](80) NULL,
	[Other Provider Identifier_29] [varchar](20) NULL,
	[Other Provider Identifier Type Code_29] [varchar](2) NULL,
	[Other Provider Identifier State_29] [varchar](2) NULL,
	[Other Provider Identifier Issuer_29] [varchar](80) NULL,
	[Other Provider Identifier_30] [varchar](20) NULL,
	[Other Provider Identifier Type Code_30] [varchar](2) NULL,
	[Other Provider Identifier State_30] [varchar](2) NULL,
	[Other Provider Identifier Issuer_30] [varchar](80) NULL,
	[Other Provider Identifier_31] [varchar](20) NULL,
	[Other Provider Identifier Type Code_31] [varchar](2) NULL,
	[Other Provider Identifier State_31] [varchar](2) NULL,
	[Other Provider Identifier Issuer_31] [varchar](80) NULL,
	[Other Provider Identifier_32] [varchar](20) NULL,
	[Other Provider Identifier Type Code_32] [varchar](2) NULL,
	[Other Provider Identifier State_32] [varchar](2) NULL,
	[Other Provider Identifier Issuer_32] [varchar](80) NULL,
	[Other Provider Identifier_33] [varchar](20) NULL,
	[Other Provider Identifier Type Code_33] [varchar](2) NULL,
	[Other Provider Identifier State_33] [varchar](2) NULL,
	[Other Provider Identifier Issuer_33] [varchar](80) NULL,
	[Other Provider Identifier_34] [varchar](20) NULL,
	[Other Provider Identifier Type Code_34] [varchar](2) NULL,
	[Other Provider Identifier State_34] [varchar](2) NULL,
	[Other Provider Identifier Issuer_34] [varchar](80) NULL,
	[Other Provider Identifier_35] [varchar](20) NULL,
	[Other Provider Identifier Type Code_35] [varchar](2) NULL,
	[Other Provider Identifier State_35] [varchar](2) NULL,
	[Other Provider Identifier Issuer_35] [varchar](80) NULL,
	[Other Provider Identifier_36] [varchar](20) NULL,
	[Other Provider Identifier Type Code_36] [varchar](2) NULL,
	[Other Provider Identifier State_36] [varchar](2) NULL,
	[Other Provider Identifier Issuer_36] [varchar](80) NULL,
	[Other Provider Identifier_37] [varchar](20) NULL,
	[Other Provider Identifier Type Code_37] [varchar](2) NULL,
	[Other Provider Identifier State_37] [varchar](2) NULL,
	[Other Provider Identifier Issuer_37] [varchar](80) NULL,
	[Other Provider Identifier_38] [varchar](20) NULL,
	[Other Provider Identifier Type Code_38] [varchar](2) NULL,
	[Other Provider Identifier State_38] [varchar](2) NULL,
	[Other Provider Identifier Issuer_38] [varchar](80) NULL,
	[Other Provider Identifier_39] [varchar](20) NULL,
	[Other Provider Identifier Type Code_39] [varchar](2) NULL,
	[Other Provider Identifier State_39] [varchar](2) NULL,
	[Other Provider Identifier Issuer_39] [varchar](80) NULL,
	[Other Provider Identifier_40] [varchar](20) NULL,
	[Other Provider Identifier Type Code_40] [varchar](2) NULL,
	[Other Provider Identifier State_40] [varchar](2) NULL,
	[Other Provider Identifier Issuer_40] [varchar](80) NULL,
	[Other Provider Identifier_41] [varchar](20) NULL,
	[Other Provider Identifier Type Code_41] [varchar](2) NULL,
	[Other Provider Identifier State_41] [varchar](2) NULL,
	[Other Provider Identifier Issuer_41] [varchar](80) NULL,
	[Other Provider Identifier_42] [varchar](20) NULL,
	[Other Provider Identifier Type Code_42] [varchar](2) NULL,
	[Other Provider Identifier State_42] [varchar](2) NULL,
	[Other Provider Identifier Issuer_42] [varchar](80) NULL,
	[Other Provider Identifier_43] [varchar](20) NULL,
	[Other Provider Identifier Type Code_43] [varchar](2) NULL,
	[Other Provider Identifier State_43] [varchar](2) NULL,
	[Other Provider Identifier Issuer_43] [varchar](80) NULL,
	[Other Provider Identifier_44] [varchar](20) NULL,
	[Other Provider Identifier Type Code_44] [varchar](2) NULL,
	[Other Provider Identifier State_44] [varchar](2) NULL,
	[Other Provider Identifier Issuer_44] [varchar](80) NULL,
	[Other Provider Identifier_45] [varchar](20) NULL,
	[Other Provider Identifier Type Code_45] [varchar](2) NULL,
	[Other Provider Identifier State_45] [varchar](2) NULL,
	[Other Provider Identifier Issuer_45] [varchar](80) NULL,
	[Other Provider Identifier_46] [varchar](20) NULL,
	[Other Provider Identifier Type Code_46] [varchar](2) NULL,
	[Other Provider Identifier State_46] [varchar](2) NULL,
	[Other Provider Identifier Issuer_46] [varchar](80) NULL,
	[Other Provider Identifier_47] [varchar](20) NULL,
	[Other Provider Identifier Type Code_47] [varchar](2) NULL,
	[Other Provider Identifier State_47] [varchar](2) NULL,
	[Other Provider Identifier Issuer_47] [varchar](80) NULL,
	[Other Provider Identifier_48] [varchar](20) NULL,
	[Other Provider Identifier Type Code_48] [varchar](2) NULL,
	[Other Provider Identifier State_48] [varchar](2) NULL,
	[Other Provider Identifier Issuer_48] [varchar](80) NULL,
	[Other Provider Identifier_49] [varchar](20) NULL,
	[Other Provider Identifier Type Code_49] [varchar](2) NULL,
	[Other Provider Identifier State_49] [varchar](2) NULL,
	[Other Provider Identifier Issuer_49] [varchar](80) NULL,
	[Other Provider Identifier_50] [varchar](20) NULL,
	[Other Provider Identifier Type Code_50] [varchar](2) NULL,
	[Other Provider Identifier State_50] [varchar](2) NULL,
	[Other Provider Identifier Issuer_50] [varchar](80) NULL,
	[Is Sole Proprietor] [varchar](1) NULL,
	[Is Organization Subpart] [varchar](1) NULL,
	[Parent Organization LBN] [varchar](70) NULL,
	[Parent Organization TIN] [varchar](9) NULL,
	[Authorized Official Name Prefix Text] [varchar](5) NULL,
	[Authorized Official Name Suffix Text] [varchar](5) NULL,
	[Authorized Official Credential Text] [varchar](20) NULL,
	[Healthcare Provider Taxonomy Group_1] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_2] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_3] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_4] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_5] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_6] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_7] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_8] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_9] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_10] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_11] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_12] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_13] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_14] [varchar](70) NULL,
	[Healthcare Provider Taxonomy Group_15] [varchar](70) NULL,
	[us_business_practice_location_zip_code_5]  AS (case when isnumeric([Provider Business Practice Location Address Postal Code])=(1) AND [Provider Business Practice Location Address Country Code (If outside US)]='US' then CONVERT([int],substring([Provider Business Practice Location Address Postal Code],(1),(5)),(0))  end) PERSISTED,
 CONSTRAINT [PK_MedicareProviders] PRIMARY KEY CLUSTERED 
(
	[NPI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Physicians](
	[NPI] [int] NOT NULL,
	[PAC ID] [varchar](10) NULL,
	[Professional Enrollment ID] [varchar](15) NULL,
	[Last Name] [varchar](35) NULL,
	[First Name] [varchar](25) NULL,
	[Middle Name] [varchar](25) NULL,
	[Suffix] [varchar](4) NULL,
	[Gender] [varchar](1) NULL,
	[Credential] [varchar](3) NULL,
	[Medical school name] [varchar](100) NULL,
	[Graduation year] [smallint] NULL,
	[Primary specialty] [varchar](50) NULL,
	[Secondary specialty 1] [varchar](50) NULL,
	[Secondary specialty 2] [varchar](50) NULL,
	[Secondary specialty 3] [varchar](50) NULL,
	[Secondary specialty 4] [varchar](50) NULL,
	[All secondary specialties] [varchar](200) NULL,
	[Organization legal name] [varchar](70) NULL,
	[Organization DBA name] [varchar](70) NULL,
	[Group Practice PAC ID] [varchar](10) NULL,
	[Number of Group Practice members] [smallint] NULL,
	[Line 1 Street Address] [varchar](55) NULL,
	[Line 2 Street Address] [varchar](55) NULL,
	[Marker of address line 2 suppression] [varchar](1) NULL,
	[City] [varchar](30) NULL,
	[State] [varchar](2) NULL,
	[Zip Code] [varchar](9) NULL,
	[Claims based hospital affiliation CCN 1] [int] NULL,
	[Claims based hospital affiliation LBN 1] [varchar](70) NULL,
	[Claims based hospital affiliation CCN 2] [int] NULL,
	[Claims based hospital affiliation LBN 2] [varchar](70) NULL,
	[Claims based hospital affiliation CCN 3] [int] NULL,
	[Claims based hospital affiliation LBN 3] [varchar](70) NULL,
	[Claims based hospital affiliation CCN 4] [int] NULL,
	[Claims based hospital affiliation LBN 4] [varchar](70) NULL,
	[Claims based hospital affiliation CCN 5] [int] NULL,
	[Claims based hospital affiliation LBN 5] [varchar](70) NULL,
	[Professional accepts Medicare Assignment] [varchar](1) NULL,
	[Participating in eRx] [varchar](1) NULL,
	[Participating in PQRS] [varchar](1) NULL,
	[Participating in EHR] [varchar](1) NULL,
	[Received PQRS Maintenance of Certification Program Incentive] [varchar](1) NULL,
	[Participated in Million Hearts] [varchar](1) NULL,
	[LastModifiedDate] [datetime] NULL,
 CONSTRAINT [PK_Physicians] PRIMARY KEY CLUSTERED 
(
	[NPI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [dbo].[Physicians]  WITH CHECK ADD  CONSTRAINT [FK_Physicians_MedicareProviders] FOREIGN KEY([NPI]) REFERENCES [dbo].[MedicareProviders] ([NPI])
ALTER TABLE [dbo].[Physicians] CHECK CONSTRAINT [FK_Physicians_MedicareProviders]
ALTER TABLE [dbo].[Physicians] ADD  CONSTRAINT [DF_Physicians_LastModifiedDate]  DEFAULT (getdate()) FOR [LastModifiedDate]
CREATE NONCLUSTERED INDEX [IX_Physicians_GroupPracticePACID] ON [dbo].[Physicians] 
(
	[Group Practice PAC ID] ASC
)
INCLUDE ( [NPI]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

CREATE TABLE [dbo].[MedicareProvidersUtilizationAndPayments](
	[npi] [int] NOT NULL,
	[year] [int] NOT NULL,
	[place_of_service] [varchar](1) NOT NULL,
	[hcpcs_code] [varchar](5) NOT NULL,
	[line_srvc_cnt] [float] NULL,
	[bene_unique_cnt] [int] NULL,
	[bene_day_srvc_cnt] [int] NULL,
	[average_medicare_allowed_amt] [float] NULL,
	[stdev_medicare_allowed_amt] [float] NULL,
	[average_submitted_chrg_amt] [float] NULL,
	[stdev_submitted_chrg_amt] [float] NULL,
	[average_medicare_payment_amt] [float] NULL,
	[stdev_medicare_payment_amt] [float] NULL,
	[average_medicare_standard_amt] [float] NULL,
 CONSTRAINT [PK_MedicareProvidersUtilizationAndPayments] PRIMARY KEY CLUSTERED 
(
	[npi] ASC,
	[year] ASC,
	[place_of_service] ASC,
	[hcpcs_code] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [dbo].[MedicareProvidersUtilizationAndPayments]  WITH CHECK ADD  CONSTRAINT [FK_MedicareProvidersUtilizationAndPayments_MedicareProviders] FOREIGN KEY([npi]) REFERENCES [dbo].[MedicareProviders] ([NPI])
ALTER TABLE [dbo].[MedicareProvidersUtilizationAndPayments] CHECK CONSTRAINT [FK_MedicareProvidersUtilizationAndPayments_MedicareProviders]
CREATE NONCLUSTERED INDEX [IX_MedicareProvidersUtilizationAndPayments_HCPCS] ON [dbo].[MedicareProvidersUtilizationAndPayments] 
(
	[hcpcs_code] ASC
)
INCLUDE ( [year]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MedicareProvidersUtilizationAndPayments_Year] ON [dbo].[MedicareProvidersUtilizationAndPayments] 
(
	[year] ASC
)
INCLUDE ( [hcpcs_code]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

CREATE TABLE [dbo].[MedicareProvidersAggregates](
	[npi] [int] NOT NULL,
	[year] [smallint] NOT NULL,
	[number_of_hcpcs] [int] NULL,
	[total_services] [real] NULL,
	[total_unique_benes] [int] NULL,
	[total_submitted_chrg_amt] [real] NULL,
	[total_medicare_allowed_amt] [real] NULL,
	[total_medicare_payment_amt] [real] NULL,
	[total_medicare_stnd_amt] [real] NULL,
	[drug_suppress_indicator] [varchar](1) NULL,
	[number_of_drug_hcpcs] [int] NULL,
	[total_drug_services] [real] NULL,
	[total_drug_unique_benes] [int] NULL,
	[total_drug_submitted_chrg_amt] [real] NULL,
	[total_drug_medicare_allowed_amt] [real] NULL,
	[total_drug_medicare_payment_amt] [real] NULL,
	[total_drug_medicare_stnd_amt] [real] NULL,
	[med_suppress_indicator] [varchar](1) NULL,
	[number_of_med_hcpcs] [int] NULL,
	[total_med_services] [real] NULL,
	[total_med_unique_benes] [int] NULL,
	[total_med_submitted_chrg_amt] [real] NULL,
	[total_med_medicare_allowed_amt] [real] NULL,
	[total_med_medicare_payment_amt] [real] NULL,
	[total_med_medicare_stnd_amt] [real] NULL,
	[beneficiary_average_age] [smallint] NULL,
	[beneficiary_age_less_65_count] [int] NULL,
	[beneficiary_age_65_74_count] [int] NULL,
	[beneficiary_age_75_84_count] [int] NULL,
	[beneficiary_age_greater_84_count] [int] NULL,
	[beneficiary_female_count] [int] NULL,
	[beneficiary_male_count] [int] NULL,
	[beneficiary_race_white_count] [int] NULL,
	[beneficiary_race_black_count] [int] NULL,
	[beneficiary_race_api_count] [int] NULL,
	[beneficiary_race_hispanic_count] [int] NULL,
	[beneficiary_race_natind_count] [int] NULL,
	[beneficiary_race_other_count] [int] NULL,
	[beneficiary_nondual_count] [int] NULL,
	[beneficiary_dual_count] [int] NULL,
	[beneficiary_cc_afib_percent] [smallint] NULL,
	[beneficiary_cc_alzrdsd_percent] [smallint] NULL,
	[beneficiary_cc_asthma_percent] [smallint] NULL,
	[beneficiary_cc_cancer_percent] [smallint] NULL,
	[beneficiary_cc_chf_percent] [smallint] NULL,
	[beneficiary_cc_ckd_percent] [smallint] NULL,
	[beneficiary_cc_copd_percent] [smallint] NULL,
	[beneficiary_cc_depr_percent] [smallint] NULL,
	[beneficiary_cc_diab_percent] [smallint] NULL,
	[beneficiary_cc_hyperl_percent] [smallint] NULL,
	[beneficiary_cc_hypert_percent] [smallint] NULL,
	[beneficiary_cc_ihd_percent] [smallint] NULL,
	[beneficiary_cc_ost_percent] [smallint] NULL,
	[beneficiary_cc_raoa_percent] [smallint] NULL,
	[beneficiary_cc_schiot_percent] [smallint] NULL,
	[beneficiary_cc_strk_percent] [smallint] NULL,
	[beneficiary_average_risk_score] [real] NULL,
 CONSTRAINT [PK_MedicareProvidersAggregates] PRIMARY KEY CLUSTERED 
(
	[npi] ASC,
	[year] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [dbo].[MedicareProvidersAggregates]  WITH CHECK ADD  CONSTRAINT [FK_MedicareProvidersAggregates_MedicareProviders] FOREIGN KEY([npi]) REFERENCES [dbo].[MedicareProviders] ([NPI])
ALTER TABLE [dbo].[MedicareProvidersAggregates] CHECK CONSTRAINT [FK_MedicareProvidersAggregates_MedicareProviders]

CREATE TABLE [dbo].[HCPCSCodes](
	[HCPCS] [varchar](5) NOT NULL,
	[ShortDescription] [nvarchar](255) NULL,
	[Description] [nvarchar](max) NULL,
	[DrugIndicator] [varchar](1) NULL,
 CONSTRAINT [PK_HCPCSCodes] PRIMARY KEY CLUSTERED 
(
	[HCPCS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[ZipCodes](
	[geoid] [int] NOT NULL,
	[aland] [bigint] NULL,
	[awater] [bigint] NULL,
	[aland_sqmi] [float] NULL,
	[awater_sqmi] [float] NULL,
	[intptlat] [float] NULL,
	[intptlong] [float] NULL,
	[point] [geography] NULL,
 CONSTRAINT [PK_ZipCodes] PRIMARY KEY CLUSTERED 
(
	[geoid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TRIGGER [dbo].[tr_ZipCodesUpdatePoints] 
   ON [dbo].[ZipCodes] 
   AFTER INSERT, UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    UPDATE Z
    SET Z.point = geography::Point(I.intptlat, I.intptlong, 4326)
    FROM inserted I
    INNER JOIN ZipCodes Z
    ON I.geoid = Z.geoid
    WHERE I.intptlat IS NOT NULL
    AND I.intptlong IS NOT NULL;

END

GO

CREATE VIEW [dbo].[MedicareExtendedProviders]
AS
SELECT     dbo.MedicareProviders.NPI, dbo.MedicareProviders.[Entity Type Code], dbo.MedicareProviders.[Replacement NPI], dbo.MedicareProviders.[Employer Identification Number (EIN)], 
                      dbo.MedicareProviders.[Provider Organization Name (Legal Business Name)], dbo.MedicareProviders.[Provider Last Name (Legal Name)], dbo.MedicareProviders.[Provider First Name], 
                      dbo.MedicareProviders.[Provider Middle Name], dbo.MedicareProviders.[Provider Name Prefix Text], dbo.MedicareProviders.[Provider Name Suffix Text], 
                      dbo.MedicareProviders.[Provider Credential Text], dbo.MedicareProviders.[Provider Other Organization Name], dbo.MedicareProviders.[Provider Other Organization Name Type Code], 
                      dbo.MedicareProviders.[Provider Other Last Name], dbo.MedicareProviders.[Provider Other First Name], dbo.MedicareProviders.[Provider Other Middle Name], 
                      dbo.MedicareProviders.[Provider Other Name Prefix Text], dbo.MedicareProviders.[Provider Other Name Suffix Text], dbo.MedicareProviders.[Provider Other Credential Text], 
                      dbo.MedicareProviders.[Provider Other Last Name Type Code], dbo.MedicareProviders.[Provider First Line Business Mailing Address], 
                      dbo.MedicareProviders.[Provider Second Line Business Mailing Address], dbo.MedicareProviders.[Provider Business Mailing Address City Name], 
                      dbo.MedicareProviders.[Provider Business Mailing Address State Name], dbo.MedicareProviders.[Provider Business Mailing Address Postal Code], 
                      dbo.MedicareProviders.[Provider Business Mailing Address Country Code (If outside US)], dbo.MedicareProviders.[Provider Business Mailing Address Telephone Number], 
                      dbo.MedicareProviders.[Provider Business Mailing Address Fax Number], dbo.MedicareProviders.[Provider First Line Business Practice Location Address], 
                      dbo.MedicareProviders.[Provider Second Line Business Practice Location Address], dbo.MedicareProviders.[Provider Business Practice Location Address City Name], 
                      dbo.MedicareProviders.[Provider Business Practice Location Address State Name], dbo.MedicareProviders.[Provider Business Practice Location Address Postal Code], 
                      dbo.MedicareProviders.[Provider Business Practice Location Address Country Code (If outside US)], dbo.MedicareProviders.[Provider Business Practice Location Address Telephone Number], 
                      dbo.MedicareProviders.[Provider Business Practice Location Address Fax Number], dbo.MedicareProviders.[Provider Enumeration Date], dbo.MedicareProviders.[Last Update Date], 
                      dbo.MedicareProviders.[NPI Deactivation Reason Code], dbo.MedicareProviders.[NPI Deactivation Date], dbo.MedicareProviders.[NPI Reactivation Date], 
                      dbo.MedicareProviders.[Provider Gender Code], dbo.MedicareProviders.[Authorized Official Last Name], dbo.MedicareProviders.[Authorized Official First Name], 
                      dbo.MedicareProviders.[Authorized Official Middle Name], dbo.MedicareProviders.[Authorized Official Title or Position], dbo.MedicareProviders.[Authorized Official Telephone Number], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_1], dbo.MedicareProviders.[Provider License Number_1], dbo.MedicareProviders.[Provider License Number State Code_1], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_1], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_2], dbo.MedicareProviders.[Provider License Number_2], 
                      dbo.MedicareProviders.[Provider License Number State Code_2], dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_2], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_3], dbo.MedicareProviders.[Provider License Number_3], dbo.MedicareProviders.[Provider License Number State Code_3], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_3], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_4], dbo.MedicareProviders.[Provider License Number_4], 
                      dbo.MedicareProviders.[Provider License Number State Code_4], dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_4], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_5], dbo.MedicareProviders.[Provider License Number_5], dbo.MedicareProviders.[Provider License Number State Code_5], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_5], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_6], dbo.MedicareProviders.[Provider License Number_6], 
                      dbo.MedicareProviders.[Provider License Number State Code_6], dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_6], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_7], dbo.MedicareProviders.[Provider License Number_7], dbo.MedicareProviders.[Provider License Number State Code_7], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_7], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_8], dbo.MedicareProviders.[Provider License Number_8], 
                      dbo.MedicareProviders.[Provider License Number State Code_8], dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_8], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_9], dbo.MedicareProviders.[Provider License Number_9], dbo.MedicareProviders.[Provider License Number State Code_9], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_9], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_10], dbo.MedicareProviders.[Provider License Number_10], 
                      dbo.MedicareProviders.[Provider License Number State Code_10], dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_10], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_11], dbo.MedicareProviders.[Provider License Number_11], dbo.MedicareProviders.[Provider License Number State Code_11], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_11], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_12], 
                      dbo.MedicareProviders.[Provider License Number_12], dbo.MedicareProviders.[Provider License Number State Code_12], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_12], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_13], 
                      dbo.MedicareProviders.[Provider License Number_13], dbo.MedicareProviders.[Provider License Number State Code_13], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_13], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_14], 
                      dbo.MedicareProviders.[Provider License Number_14], dbo.MedicareProviders.[Provider License Number State Code_14], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_14], dbo.MedicareProviders.[Healthcare Provider Taxonomy Code_15], 
                      dbo.MedicareProviders.[Provider License Number_15], dbo.MedicareProviders.[Provider License Number State Code_15], 
                      dbo.MedicareProviders.[Healthcare Provider Primary Taxonomy Switch_15], dbo.MedicareProviders.[Other Provider Identifier_1], dbo.MedicareProviders.[Other Provider Identifier Type Code_1], 
                      dbo.MedicareProviders.[Other Provider Identifier State_1], dbo.MedicareProviders.[Other Provider Identifier Issuer_1], dbo.MedicareProviders.[Other Provider Identifier_2], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_2], dbo.MedicareProviders.[Other Provider Identifier State_2], dbo.MedicareProviders.[Other Provider Identifier Issuer_2], 
                      dbo.MedicareProviders.[Other Provider Identifier_3], dbo.MedicareProviders.[Other Provider Identifier Type Code_3], dbo.MedicareProviders.[Other Provider Identifier State_3], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_3], dbo.MedicareProviders.[Other Provider Identifier_4], dbo.MedicareProviders.[Other Provider Identifier Type Code_4], 
                      dbo.MedicareProviders.[Other Provider Identifier State_4], dbo.MedicareProviders.[Other Provider Identifier Issuer_4], dbo.MedicareProviders.[Other Provider Identifier_5], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_5], dbo.MedicareProviders.[Other Provider Identifier State_5], dbo.MedicareProviders.[Other Provider Identifier Issuer_5], 
                      dbo.MedicareProviders.[Other Provider Identifier_6], dbo.MedicareProviders.[Other Provider Identifier Type Code_6], dbo.MedicareProviders.[Other Provider Identifier State_6], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_6], dbo.MedicareProviders.[Other Provider Identifier_7], dbo.MedicareProviders.[Other Provider Identifier Type Code_7], 
                      dbo.MedicareProviders.[Other Provider Identifier State_7], dbo.MedicareProviders.[Other Provider Identifier Issuer_7], dbo.MedicareProviders.[Other Provider Identifier_8], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_8], dbo.MedicareProviders.[Other Provider Identifier State_8], dbo.MedicareProviders.[Other Provider Identifier Issuer_8], 
                      dbo.MedicareProviders.[Other Provider Identifier_9], dbo.MedicareProviders.[Other Provider Identifier Type Code_9], dbo.MedicareProviders.[Other Provider Identifier State_9], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_9], dbo.MedicareProviders.[Other Provider Identifier_10], dbo.MedicareProviders.[Other Provider Identifier Type Code_10], 
                      dbo.MedicareProviders.[Other Provider Identifier State_10], dbo.MedicareProviders.[Other Provider Identifier Issuer_10], dbo.MedicareProviders.[Other Provider Identifier_11], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_11], dbo.MedicareProviders.[Other Provider Identifier State_11], dbo.MedicareProviders.[Other Provider Identifier Issuer_11], 
                      dbo.MedicareProviders.[Other Provider Identifier_12], dbo.MedicareProviders.[Other Provider Identifier Type Code_12], dbo.MedicareProviders.[Other Provider Identifier State_12], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_12], dbo.MedicareProviders.[Other Provider Identifier_13], dbo.MedicareProviders.[Other Provider Identifier Type Code_13], 
                      dbo.MedicareProviders.[Other Provider Identifier State_13], dbo.MedicareProviders.[Other Provider Identifier Issuer_13], dbo.MedicareProviders.[Other Provider Identifier_14], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_14], dbo.MedicareProviders.[Other Provider Identifier State_14], dbo.MedicareProviders.[Other Provider Identifier Issuer_14], 
                      dbo.MedicareProviders.[Other Provider Identifier_15], dbo.MedicareProviders.[Other Provider Identifier Type Code_15], dbo.MedicareProviders.[Other Provider Identifier State_15], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_15], dbo.MedicareProviders.[Other Provider Identifier_16], dbo.MedicareProviders.[Other Provider Identifier Type Code_16], 
                      dbo.MedicareProviders.[Other Provider Identifier State_16], dbo.MedicareProviders.[Other Provider Identifier Issuer_16], dbo.MedicareProviders.[Other Provider Identifier_17], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_17], dbo.MedicareProviders.[Other Provider Identifier State_17], dbo.MedicareProviders.[Other Provider Identifier Issuer_17], 
                      dbo.MedicareProviders.[Other Provider Identifier_18], dbo.MedicareProviders.[Other Provider Identifier Type Code_18], dbo.MedicareProviders.[Other Provider Identifier State_18], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_18], dbo.MedicareProviders.[Other Provider Identifier_19], dbo.MedicareProviders.[Other Provider Identifier Type Code_19], 
                      dbo.MedicareProviders.[Other Provider Identifier State_19], dbo.MedicareProviders.[Other Provider Identifier Issuer_19], dbo.MedicareProviders.[Other Provider Identifier_20], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_20], dbo.MedicareProviders.[Other Provider Identifier State_20], dbo.MedicareProviders.[Other Provider Identifier Issuer_20], 
                      dbo.MedicareProviders.[Other Provider Identifier_21], dbo.MedicareProviders.[Other Provider Identifier Type Code_21], dbo.MedicareProviders.[Other Provider Identifier State_21], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_21], dbo.MedicareProviders.[Other Provider Identifier_22], dbo.MedicareProviders.[Other Provider Identifier Type Code_22], 
                      dbo.MedicareProviders.[Other Provider Identifier State_22], dbo.MedicareProviders.[Other Provider Identifier Issuer_22], dbo.MedicareProviders.[Other Provider Identifier_23], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_23], dbo.MedicareProviders.[Other Provider Identifier State_23], dbo.MedicareProviders.[Other Provider Identifier Issuer_23], 
                      dbo.MedicareProviders.[Other Provider Identifier_24], dbo.MedicareProviders.[Other Provider Identifier Type Code_24], dbo.MedicareProviders.[Other Provider Identifier State_24], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_24], dbo.MedicareProviders.[Other Provider Identifier_25], dbo.MedicareProviders.[Other Provider Identifier Type Code_25], 
                      dbo.MedicareProviders.[Other Provider Identifier State_25], dbo.MedicareProviders.[Other Provider Identifier Issuer_25], dbo.MedicareProviders.[Other Provider Identifier_26], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_26], dbo.MedicareProviders.[Other Provider Identifier State_26], dbo.MedicareProviders.[Other Provider Identifier Issuer_26], 
                      dbo.MedicareProviders.[Other Provider Identifier_27], dbo.MedicareProviders.[Other Provider Identifier Type Code_27], dbo.MedicareProviders.[Other Provider Identifier State_27], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_27], dbo.MedicareProviders.[Other Provider Identifier_28], dbo.MedicareProviders.[Other Provider Identifier Type Code_28], 
                      dbo.MedicareProviders.[Other Provider Identifier State_28], dbo.MedicareProviders.[Other Provider Identifier Issuer_28], dbo.MedicareProviders.[Other Provider Identifier_29], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_29], dbo.MedicareProviders.[Other Provider Identifier State_29], dbo.MedicareProviders.[Other Provider Identifier Issuer_29], 
                      dbo.MedicareProviders.[Other Provider Identifier_30], dbo.MedicareProviders.[Other Provider Identifier Type Code_30], dbo.MedicareProviders.[Other Provider Identifier State_30], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_30], dbo.MedicareProviders.[Other Provider Identifier_31], dbo.MedicareProviders.[Other Provider Identifier Type Code_31], 
                      dbo.MedicareProviders.[Other Provider Identifier State_31], dbo.MedicareProviders.[Other Provider Identifier Issuer_31], dbo.MedicareProviders.[Other Provider Identifier_32], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_32], dbo.MedicareProviders.[Other Provider Identifier State_32], dbo.MedicareProviders.[Other Provider Identifier Issuer_32], 
                      dbo.MedicareProviders.[Other Provider Identifier_33], dbo.MedicareProviders.[Other Provider Identifier Type Code_33], dbo.MedicareProviders.[Other Provider Identifier State_33], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_33], dbo.MedicareProviders.[Other Provider Identifier_34], dbo.MedicareProviders.[Other Provider Identifier Type Code_34], 
                      dbo.MedicareProviders.[Other Provider Identifier State_34], dbo.MedicareProviders.[Other Provider Identifier Issuer_34], dbo.MedicareProviders.[Other Provider Identifier_35], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_35], dbo.MedicareProviders.[Other Provider Identifier State_35], dbo.MedicareProviders.[Other Provider Identifier Issuer_35], 
                      dbo.MedicareProviders.[Other Provider Identifier_36], dbo.MedicareProviders.[Other Provider Identifier Type Code_36], dbo.MedicareProviders.[Other Provider Identifier State_36], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_36], dbo.MedicareProviders.[Other Provider Identifier_37], dbo.MedicareProviders.[Other Provider Identifier Type Code_37], 
                      dbo.MedicareProviders.[Other Provider Identifier State_37], dbo.MedicareProviders.[Other Provider Identifier Issuer_37], dbo.MedicareProviders.[Other Provider Identifier_38], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_38], dbo.MedicareProviders.[Other Provider Identifier State_38], dbo.MedicareProviders.[Other Provider Identifier Issuer_38], 
                      dbo.MedicareProviders.[Other Provider Identifier_39], dbo.MedicareProviders.[Other Provider Identifier Type Code_39], dbo.MedicareProviders.[Other Provider Identifier State_39], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_39], dbo.MedicareProviders.[Other Provider Identifier_40], dbo.MedicareProviders.[Other Provider Identifier Type Code_40], 
                      dbo.MedicareProviders.[Other Provider Identifier State_40], dbo.MedicareProviders.[Other Provider Identifier Issuer_40], dbo.MedicareProviders.[Other Provider Identifier_41], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_41], dbo.MedicareProviders.[Other Provider Identifier State_41], dbo.MedicareProviders.[Other Provider Identifier Issuer_41], 
                      dbo.MedicareProviders.[Other Provider Identifier_42], dbo.MedicareProviders.[Other Provider Identifier Type Code_42], dbo.MedicareProviders.[Other Provider Identifier State_42], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_42], dbo.MedicareProviders.[Other Provider Identifier_43], dbo.MedicareProviders.[Other Provider Identifier Type Code_43], 
                      dbo.MedicareProviders.[Other Provider Identifier State_43], dbo.MedicareProviders.[Other Provider Identifier Issuer_43], dbo.MedicareProviders.[Other Provider Identifier_44], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_44], dbo.MedicareProviders.[Other Provider Identifier State_44], dbo.MedicareProviders.[Other Provider Identifier Issuer_44], 
                      dbo.MedicareProviders.[Other Provider Identifier_45], dbo.MedicareProviders.[Other Provider Identifier Type Code_45], dbo.MedicareProviders.[Other Provider Identifier State_45], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_45], dbo.MedicareProviders.[Other Provider Identifier_46], dbo.MedicareProviders.[Other Provider Identifier Type Code_46], 
                      dbo.MedicareProviders.[Other Provider Identifier State_46], dbo.MedicareProviders.[Other Provider Identifier Issuer_46], dbo.MedicareProviders.[Other Provider Identifier_47], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_47], dbo.MedicareProviders.[Other Provider Identifier State_47], dbo.MedicareProviders.[Other Provider Identifier Issuer_47], 
                      dbo.MedicareProviders.[Other Provider Identifier_48], dbo.MedicareProviders.[Other Provider Identifier Type Code_48], dbo.MedicareProviders.[Other Provider Identifier State_48], 
                      dbo.MedicareProviders.[Other Provider Identifier Issuer_48], dbo.MedicareProviders.[Other Provider Identifier_49], dbo.MedicareProviders.[Other Provider Identifier Type Code_49], 
                      dbo.MedicareProviders.[Other Provider Identifier State_49], dbo.MedicareProviders.[Other Provider Identifier Issuer_49], dbo.MedicareProviders.[Other Provider Identifier_50], 
                      dbo.MedicareProviders.[Other Provider Identifier Type Code_50], dbo.MedicareProviders.[Other Provider Identifier State_50], dbo.MedicareProviders.[Other Provider Identifier Issuer_50], 
                      dbo.MedicareProviders.[Is Sole Proprietor], dbo.MedicareProviders.[Is Organization Subpart], dbo.MedicareProviders.[Parent Organization LBN], dbo.MedicareProviders.[Parent Organization TIN], 
                      dbo.MedicareProviders.[Authorized Official Name Prefix Text], dbo.MedicareProviders.[Authorized Official Name Suffix Text], dbo.MedicareProviders.[Authorized Official Credential Text], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_1], dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_2], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_3], dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_4], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_5], dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_6], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_7], dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_8], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_9], dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_10], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_11], dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_12], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_13], dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_14], 
                      dbo.MedicareProviders.[Healthcare Provider Taxonomy Group_15], dbo.MedicareProviders.us_business_practice_location_zip_code_5, dbo.Physicians.[PAC ID], 
                      dbo.Physicians.[Professional Enrollment ID], dbo.Physicians.[Medical school name], dbo.Physicians.[Graduation year], dbo.Physicians.[Primary specialty], dbo.Physicians.[Secondary specialty 1], 
                      dbo.Physicians.[Secondary specialty 2], dbo.Physicians.[Secondary specialty 3], dbo.Physicians.[Secondary specialty 4], dbo.Physicians.[All secondary specialties], 
                      dbo.Physicians.[Organization legal name], dbo.Physicians.[Organization DBA name], dbo.Physicians.[Group Practice PAC ID], dbo.Physicians.[Number of Group Practice members], 
                      dbo.Physicians.[Claims based hospital affiliation CCN 1], dbo.Physicians.[Claims based hospital affiliation LBN 1], dbo.Physicians.[Claims based hospital affiliation CCN 2], 
                      dbo.Physicians.[Claims based hospital affiliation LBN 2], dbo.Physicians.[Claims based hospital affiliation CCN 3], dbo.Physicians.[Claims based hospital affiliation LBN 3], 
                      dbo.Physicians.[Claims based hospital affiliation CCN 4], dbo.Physicians.[Claims based hospital affiliation LBN 4], dbo.Physicians.[Claims based hospital affiliation CCN 5], 
                      dbo.Physicians.[Claims based hospital affiliation LBN 5], dbo.Physicians.[Professional accepts Medicare Assignment], dbo.Physicians.[Participating in eRx], dbo.Physicians.[Participating in PQRS], 
                      dbo.Physicians.[Participating in EHR], dbo.Physicians.[Received PQRS Maintenance of Certification Program Incentive], dbo.Physicians.[Participated in Million Hearts]
FROM         dbo.MedicareProviders LEFT OUTER JOIN dbo.Physicians ON dbo.MedicareProviders.NPI = dbo.Physicians.NPI
GO

CREATE VIEW [dbo].[MedicareExtendedProvidersAggregates]
AS
SELECT     dbo.MedicareProvidersAggregates.*
FROM         dbo.MedicareProvidersAggregates
GO

CREATE VIEW [dbo].[MedicareExtendedUtilizationAndPayments]
AS
SELECT     dbo.MedicareProvidersUtilizationAndPayments.*, dbo.HCPCSCodes.ShortDescription, dbo.HCPCSCodes.Description, dbo.HCPCSCodes.DrugIndicator
FROM         dbo.MedicareProvidersUtilizationAndPayments LEFT OUTER JOIN dbo.HCPCSCodes ON dbo.MedicareProvidersUtilizationAndPayments.hcpcs_code = dbo.HCPCSCodes.HCPCS