//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Medicare
{
    using System;
    using System.Collections.Generic;
    
    public partial class jqGridSavedSearchHistory
    {
        public int ID { get; set; }
        public string SearchType { get; set; }
        public int ContactID { get; set; }
        public string Name { get; set; }
        public string Search { get; set; }
        public string Filter { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
    }
}
