//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Medicare
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicareExtendedPhysician
    {
        public int NPI { get; set; }
        public string PAC_ID { get; set; }
        public string Professional_Enrollment_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Suffix { get; set; }
        public string Gender { get; set; }
        public string Credential { get; set; }
        public string Medical_school_name { get; set; }
        public Nullable<short> Graduation_year { get; set; }
        public string Primary_specialty { get; set; }
        public string Secondary_specialty_1 { get; set; }
        public string Secondary_specialty_2 { get; set; }
        public string Secondary_specialty_3 { get; set; }
        public string Secondary_specialty_4 { get; set; }
        public string All_secondary_specialties { get; set; }
        public string Organization_legal_name { get; set; }
        public string Organization_DBA_name { get; set; }
        public string Group_Practice_PAC_ID { get; set; }
        public Nullable<short> Number_of_Group_Practice_members { get; set; }
        public string Line_1_Street_Address { get; set; }
        public string Line_2_Street_Address { get; set; }
        public string Marker_of_address_line_2_suppression { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<int> Claims_based_hospital_affiliation_CCN_1 { get; set; }
        public string Claims_based_hospital_affiliation_LBN_1 { get; set; }
        public Nullable<int> Claims_based_hospital_affiliation_CCN_2 { get; set; }
        public string Claims_based_hospital_affiliation_LBN_2 { get; set; }
        public Nullable<int> Claims_based_hospital_affiliation_CCN_3 { get; set; }
        public string Claims_based_hospital_affiliation_LBN_3 { get; set; }
        public Nullable<int> Claims_based_hospital_affiliation_CCN_4 { get; set; }
        public string Claims_based_hospital_affiliation_LBN_4 { get; set; }
        public Nullable<int> Claims_based_hospital_affiliation_CCN_5 { get; set; }
        public string Claims_based_hospital_affiliation_LBN_5 { get; set; }
        public string Professional_accepts_Medicare_Assignment { get; set; }
        public string Participating_in_eRx { get; set; }
        public string Participating_in_PQRS { get; set; }
        public string Participating_in_EHR { get; set; }
        public string Received_PQRS_Maintenance_of_Certification_Program_Incentive { get; set; }
        public string Participated_in_Million_Hearts { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
