//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Medicare
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicareExtendedUtilizationAndPayment
    {
        public int npi { get; set; }
        public int year { get; set; }
        public string place_of_service { get; set; }
        public string hcpcs_code { get; set; }
        public Nullable<double> line_srvc_cnt { get; set; }
        public Nullable<int> bene_unique_cnt { get; set; }
        public Nullable<int> bene_day_srvc_cnt { get; set; }
        public Nullable<double> average_medicare_allowed_amt { get; set; }
        public Nullable<double> stdev_medicare_allowed_amt { get; set; }
        public Nullable<double> average_submitted_chrg_amt { get; set; }
        public Nullable<double> stdev_submitted_chrg_amt { get; set; }
        public Nullable<double> average_medicare_payment_amt { get; set; }
        public Nullable<double> stdev_medicare_payment_amt { get; set; }
        public Nullable<double> average_medicare_standard_amt { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string DrugIndicator { get; set; }
    }
}
