//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Medicare
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicareExtendedProvidersAggregate
    {
        public int npi { get; set; }
        public short year { get; set; }
        public Nullable<int> number_of_hcpcs { get; set; }
        public Nullable<float> total_services { get; set; }
        public Nullable<int> total_unique_benes { get; set; }
        public Nullable<float> total_submitted_chrg_amt { get; set; }
        public Nullable<float> total_medicare_allowed_amt { get; set; }
        public Nullable<float> total_medicare_payment_amt { get; set; }
        public Nullable<float> total_medicare_stnd_amt { get; set; }
        public string drug_suppress_indicator { get; set; }
        public Nullable<int> number_of_drug_hcpcs { get; set; }
        public Nullable<float> total_drug_services { get; set; }
        public Nullable<int> total_drug_unique_benes { get; set; }
        public Nullable<float> total_drug_submitted_chrg_amt { get; set; }
        public Nullable<float> total_drug_medicare_allowed_amt { get; set; }
        public Nullable<float> total_drug_medicare_payment_amt { get; set; }
        public Nullable<float> total_drug_medicare_stnd_amt { get; set; }
        public string med_suppress_indicator { get; set; }
        public Nullable<int> number_of_med_hcpcs { get; set; }
        public Nullable<float> total_med_services { get; set; }
        public Nullable<int> total_med_unique_benes { get; set; }
        public Nullable<float> total_med_submitted_chrg_amt { get; set; }
        public Nullable<float> total_med_medicare_allowed_amt { get; set; }
        public Nullable<float> total_med_medicare_payment_amt { get; set; }
        public Nullable<float> total_med_medicare_stnd_amt { get; set; }
        public Nullable<short> beneficiary_average_age { get; set; }
        public Nullable<int> beneficiary_age_less_65_count { get; set; }
        public Nullable<int> beneficiary_age_65_74_count { get; set; }
        public Nullable<int> beneficiary_age_75_84_count { get; set; }
        public Nullable<int> beneficiary_age_greater_84_count { get; set; }
        public Nullable<int> beneficiary_female_count { get; set; }
        public Nullable<int> beneficiary_male_count { get; set; }
        public Nullable<int> beneficiary_race_white_count { get; set; }
        public Nullable<int> beneficiary_race_black_count { get; set; }
        public Nullable<int> beneficiary_race_api_count { get; set; }
        public Nullable<int> beneficiary_race_hispanic_count { get; set; }
        public Nullable<int> beneficiary_race_natind_count { get; set; }
        public Nullable<int> beneficiary_race_other_count { get; set; }
        public Nullable<int> beneficiary_nondual_count { get; set; }
        public Nullable<int> beneficiary_dual_count { get; set; }
        public Nullable<short> beneficiary_cc_afib_percent { get; set; }
        public Nullable<short> beneficiary_cc_alzrdsd_percent { get; set; }
        public Nullable<short> beneficiary_cc_asthma_percent { get; set; }
        public Nullable<short> beneficiary_cc_cancer_percent { get; set; }
        public Nullable<short> beneficiary_cc_chf_percent { get; set; }
        public Nullable<short> beneficiary_cc_ckd_percent { get; set; }
        public Nullable<short> beneficiary_cc_copd_percent { get; set; }
        public Nullable<short> beneficiary_cc_depr_percent { get; set; }
        public Nullable<short> beneficiary_cc_diab_percent { get; set; }
        public Nullable<short> beneficiary_cc_hyperl_percent { get; set; }
        public Nullable<short> beneficiary_cc_hypert_percent { get; set; }
        public Nullable<short> beneficiary_cc_ihd_percent { get; set; }
        public Nullable<short> beneficiary_cc_ost_percent { get; set; }
        public Nullable<short> beneficiary_cc_raoa_percent { get; set; }
        public Nullable<short> beneficiary_cc_schiot_percent { get; set; }
        public Nullable<short> beneficiary_cc_strk_percent { get; set; }
        public Nullable<float> beneficiary_average_risk_score { get; set; }
        public Nullable<short> Entity_Type_Code { get; set; }
        public string Provider_Organization_Name__Legal_Business_Name_ { get; set; }
        public string Provider_Last_Name__Legal_Name_ { get; set; }
        public string Provider_First_Name { get; set; }
        public string Provider_Middle_Name { get; set; }
        public string Provider_Name_Prefix_Text { get; set; }
        public string Provider_Name_Suffix_Text { get; set; }
        public string Provider_Credential_Text { get; set; }
        public string Provider_First_Line_Business_Mailing_Address { get; set; }
        public string Provider_Second_Line_Business_Mailing_Address { get; set; }
        public string Provider_Business_Mailing_Address_City_Name { get; set; }
        public string Provider_Business_Mailing_Address_State_Name { get; set; }
        public string Provider_Business_Mailing_Address_Postal_Code { get; set; }
        public string Provider_Business_Mailing_Address_Country_Code__If_outside_US_ { get; set; }
        public string Provider_Business_Mailing_Address_Telephone_Number { get; set; }
        public string Provider_Business_Mailing_Address_Fax_Number { get; set; }
        public string Provider_First_Line_Business_Practice_Location_Address { get; set; }
        public string Provider_Second_Line_Business_Practice_Location_Address { get; set; }
        public string Provider_Business_Practice_Location_Address_City_Name { get; set; }
        public string Provider_Business_Practice_Location_Address_State_Name { get; set; }
        public string Provider_Business_Practice_Location_Address_Postal_Code { get; set; }
        public string Provider_Business_Practice_Location_Address_Country_Code__If_outside_US_ { get; set; }
        public string Provider_Business_Practice_Location_Address_Telephone_Number { get; set; }
        public string Provider_Business_Practice_Location_Address_Fax_Number { get; set; }
        public string Primary_specialty { get; set; }
        public string All_secondary_specialties { get; set; }
    }
}
